In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size=10000

In [6]:
one_hot_repr=[one_hot(word,voc_size) for word in sent]

In [7]:
one_hot_repr

[[1313, 9449, 5776, 4338],
 [1313, 9449, 5776, 9441],
 [1313, 6650, 5776, 2199],
 [8776, 4694, 1964, 5106, 8740],
 [8776, 4694, 1964, 5106, 8896],
 [8852, 1313, 661, 5776, 2243],
 [681, 5961, 3651, 5106]]

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

In [12]:
embedded_docs

array([[   0,    0,    0,    0, 1313, 9449, 5776, 4338],
       [   0,    0,    0,    0, 1313, 9449, 5776, 9441],
       [   0,    0,    0,    0, 1313, 6650, 5776, 2199],
       [   0,    0,    0, 8776, 4694, 1964, 5106, 8740],
       [   0,    0,    0, 8776, 4694, 1964, 5106, 8896],
       [   0,    0,    0, 8852, 1313,  661, 5776, 2243],
       [   0,    0,    0,    0,  681, 5961, 3651, 5106]])

In [13]:
model=Sequential()

In [14]:
model.add(Embedding(voc_size,10,input_length=sent_length))

In [15]:
model.compile('adam','mse')

In [16]:
model.predict(embedded_docs)

array([[[-0.04948656,  0.00120224,  0.04331592,  0.00411111,
          0.01759526,  0.00769603,  0.00621362, -0.04093598,
          0.030942  ,  0.02671417],
        [-0.04948656,  0.00120224,  0.04331592,  0.00411111,
          0.01759526,  0.00769603,  0.00621362, -0.04093598,
          0.030942  ,  0.02671417],
        [-0.04948656,  0.00120224,  0.04331592,  0.00411111,
          0.01759526,  0.00769603,  0.00621362, -0.04093598,
          0.030942  ,  0.02671417],
        [-0.04948656,  0.00120224,  0.04331592,  0.00411111,
          0.01759526,  0.00769603,  0.00621362, -0.04093598,
          0.030942  ,  0.02671417],
        [-0.0184754 , -0.01760844, -0.0376695 , -0.01349876,
          0.04386362,  0.03689101, -0.02084725, -0.03634974,
         -0.02992524, -0.0043951 ],
        [ 0.00094612,  0.02961607, -0.02889812,  0.04220421,
         -0.04703022,  0.03444663, -0.03046805,  0.01884003,
          0.03156469,  0.03055675],
        [ 0.04725858,  0.03171785,  0.0355901 , -0.0

In [17]:
model.predict(embedded_docs[0])

array([[[-0.04948656,  0.00120224,  0.04331592,  0.00411111,
          0.01759526,  0.00769603,  0.00621362, -0.04093598,
          0.030942  ,  0.02671417]],

       [[-0.04948656,  0.00120224,  0.04331592,  0.00411111,
          0.01759526,  0.00769603,  0.00621362, -0.04093598,
          0.030942  ,  0.02671417]],

       [[-0.04948656,  0.00120224,  0.04331592,  0.00411111,
          0.01759526,  0.00769603,  0.00621362, -0.04093598,
          0.030942  ,  0.02671417]],

       [[-0.04948656,  0.00120224,  0.04331592,  0.00411111,
          0.01759526,  0.00769603,  0.00621362, -0.04093598,
          0.030942  ,  0.02671417]],

       [[-0.0184754 , -0.01760844, -0.0376695 , -0.01349876,
          0.04386362,  0.03689101, -0.02084725, -0.03634974,
         -0.02992524, -0.0043951 ]],

       [[ 0.00094612,  0.02961607, -0.02889812,  0.04220421,
         -0.04703022,  0.03444663, -0.03046805,  0.01884003,
          0.03156469,  0.03055675]],

       [[ 0.04725858,  0.03171785,  0.03

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 1313, 9449, 5776, 4338])